<?php
ob_start();
echo "<h1>Ajouter Un Immobilier</h1>";
echo "<form action='../controller/addImmobilier.php' method='POST'>";
echo "<label for='reference'>Reference</label>";
echo "<input type='text' class='form-control' name='reference' id='reference' required><br>";
echo "<label for='proprietaire'>Proprietaire</label>";
echo "<input type='text' class='form-control' name='proprietaire' id='proprietaire' required><br>";
echo "<label for='localite'>Localite</label>";
echo "<input type='text' class='form-control' name='localite' id='localite' required><br>";
echo "<label for='nbpiece'>Nombre de piece</label>";
echo "<input type='text' class='form-control' name='nbpiece' id='nbpiece' required><br>";
echo "<label for='domaineUsage'>Domaine d'usage</label>";
echo "<select name='domaineUsage' id='domaineUsage' class='form-control' required>";
echo "<option value='bureau'>Bureau</option>";
echo "<option value='domicile'>Domicile</option>";
echo "</select><br>";
echo "<label for='nature'>Nature</label>";
echo "<select name='nature' id='nature' class='form-control' required>";
echo "<option value='appartement'>Appartement</option>";
echo "<option value='villa'>Villa</option>";
echo "</select><br>";
echo "<label for='nbEtage'>Nombre d'etage</label>";
echo "<input type='text' class='form-control' name='nbEtage' id='nbEtage' required><br>";
echo "<label for='surface'>Surface</label>";
echo "<input type='text' class='form-control' name='surface' id='surface' required><br>";
echo "<input type='submit' class='btn btn-primary' value='Ajouter'>";
echo "</form>";
$contenu = ob_get_clean();
include "template.php";
