<?php
ob_start();
echo "<h1>Immobiliers$reference</h1>";
echo "<form action='../controller/updateImmobilier.php' method='POST'>";
echo "<label for='reference'>Reference</label>";
echo "<input type='text' class='form-control' name='reference' id='reference' value='$found_immobilier[0]' required><br>";
echo "<label for='proprietaire'>Proprietaire</label>";
echo "<input type='text' class='form-control' name='proprietaire' id='proprietaire' value='$found_immobilier[1]' required><br>";
echo "<label for='localite'>Localite</label>";
echo "<input type='text' class='form-control' name='localite' id='localite' value='$found_immobilier[2]' required><br>";
echo "<label for='nbpiece'>Nombre de piece</label>";
echo "<input type='text' class='form-control' name='nbpiece' id='nbpiece' value='$found_immobilier[3]' required><br>";
echo "<label for='domaineUsage'>Domaine d'usage</label>";
echo "<select name='domaineUsage' id='domaineUsage' class='form-control' required>";
echo "<option value='bureau'>Bureau</option>";
echo "<option value='domicile'>Domicile</option>";
echo "</select><br>";
echo "<label for='nature'>Nature</label>";
echo "<select name='nature' id='nature' class='form-control' required>";
echo "<option value='appartement'>Appartement</option>";
echo "<option value='villa'>Villa</option>";
echo "</select><br>";
echo "<label for='nbEtage'>Nombre d'etage</label>";
echo "<input type='text' class='form-control' name='nbEtage' id='nbEtage' value='$found_immobilier[6]' required><br>";
echo "<label for='surface'>Surface</label>";
echo "<input type='text' class='form-control' name='surface' id='surface' value='$found_immobilier[7]' required><br>";
echo "<input type='submit' class='btn btn-primary' value='Modifier' name='ok'>";
echo "</form>";
$contenu = ob_get_clean();
include "template.php";
